### ISSUE TITLE
请教一下 emacs 中配置 python3的方法

### ISSUE THREAD

**Issue by samualle** [iuyo5678/emacs_config#1]
网上看了很多 emacs 的配置，python 环境启动后，都是默认调用了 python2（确切说是系统的 python 命令关联到了 python2），想请教一下，如何在不改变系统的 python 设置的情况下，在 emacs 里启用 python3？virtualenv 也配置过了，可是，要么没起作用，要么就是在 emacs调用 python 的 时候报错。作为新手，在emacs 中配置 python 环境的时候，挺吃力，希望能获取一些帮助，谢谢了。

**Comment by iuyo5678** [comment]
这个我测试了是可以的，我一般是用virtualenv或是virtualenvwrapper，创建一个虚拟的python环境，然后在emacs中使用，这样环境互不干扰，也方便测试，也推荐你使用，

其中virtualenv 和virtualevnwrapper安装你可以查找文档。

其中virtualenv指定python环境的命令如下：

```shell
virtualenv -p python3 nameOfEnvironment
```

virtualenvwrapper 配置python3的虚拟环境的代码如下：

```shell
which python3 #Output: /usr/bin/python3
mkvirtualenv --python=/usr/bin/python3 nameOfEnvironment
```

这时启动emacs， emacs里面配置好 elpy（具体可以查看相关文档，我的emacs配置文件已经配置好了）M-x 输入 pyenv=workon，选择刚才创建的nameOfEnvironment， 这时在你的emacs中python都会默认使用你创建虚拟环境使用的python版本，和系统的不冲突。

**Comment by wangshuaibing** [comment]
谢谢您的指点，很及时，很需要！
